# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory/inventory.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19inventory/inventory.proto\x12\tinventory\"%\n\x11InventoryReserved\x12\x10\n\x08order_id\x18\x01 \x01(\t\"%\n\x11InventoryReleased\x12\x10\n\x08order_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory.inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORYRESERVED']._serialized_start=40
  _globals['_INVENTORYRESERVED']._serialized_end=77
  _globals['_INVENTORYRELEASED']._serialized_start=79
  _globals['_INVENTORYRELEASED']._serialized_end=116
# @@protoc_insertion_point(module_scope)
